# Generated by Django 5.2.6 on 2025-09-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
